### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by MacgyverJohnson** [singleNeuron/LockNotification#2]
Hello @singleNeuron
Can I use this to group persistent notifications from different apps( by using different channelkey or other ways) to remove clutter from notification panel and apply group summary? for example see this [AutoNotification - Create Grouped Notifications on Android 7 and above | AutoApps Forums ](https://forum.joaoapps.com/index.php?threads/create-grouped-notifications-on-android-7-and-above.7124/)
For example tasker autonotification plugin can do this (check above link) but can do that to only notifications created by autonotification, not by 3rd party apps...
Best Regards

**Comment by Cryolitia** [comment]
Please do not bother us by using "@", not all contributors are able to answer your question. And I will get E-mail and Telegram notification immediately as soon as anyone post an issue so it's unnecessary.

No, it's designed for chaging Notifications in the app that posting them itself. For example, An application named A post a Notification, and after the LockNotification's decorating by Xposed, the Notification would still be posted by A. It cannot change Notifications' poster.

I think you may like to check it: https://play.google.com/store/apps/details?id=com.catchingnow.np

After all, thanks for considerating my App.
